-- MySQL Script generated by MySQL Workbench
-- 06/30/15 20:45:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema datos2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datos2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datos2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `datos2` ;

-- -----------------------------------------------------
-- Table `datos2`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datos2`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datos2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datos2`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `remember_token` VARCHAR(45) NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`, `profile_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_users_profiles`
    FOREIGN KEY (`profile_id`)
    REFERENCES `datos2`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datos2`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datos2`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datos2`.`profiles_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datos2`.`profiles_roles` (
  `profile_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`, `role_id`),
  CONSTRAINT `fk_profiles_has_roles_profiles`
    FOREIGN KEY (`profile_id`)
    REFERENCES `datos2`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_has_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `datos2`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
